Adjective_1 = input("Adjective: ")
Verb_1 = input("Verb (Past Tense): ")
Adjective_2 = input("Adjective: ")
Adjective_3 = input("Adjective: ")
Adjective_4 = input("Adjective: ")
Noun_1 = input("Noun: ")
Body_Part = input("Body Part: ")
Adverb_1 = input("Adverb: ")
print("There was a " + Adjective_1 + " man who " + Verb_1 + " across a " + Adjective_2 + " street.")
print("He didn't see the " + Noun_1 + " when he " + Adverb_1 + " " + Verb_1 + ".")
print("To this day, no one can figure out if he was " + Adjective_3 + " or if he was just plain " + Adjective_4 + ",")
print("All we really know, is wherever he is and whatever he was, now he's missing a/an " + Body_Part + ",")
print ("And the " + Noun_1 + " has never been the same.")
